title: <p align="center"> Sai Krishna </p>
logo: /assets/img/IMG_20150725_204912~2.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href=">LinkedIn</a> |
  <a href="https://github.com/Sai-Krishna-Rali">GitHub</a>
  
  <br>   
 I am working as a presales consultant at Impelsys Pvt Limited
  <br>
  </p>



theme: jekyll-theme-minimal
